language: node_js
sudo: false
node_js:
- '4.3.1'
cache:
  directories:
    - node_modules
before_install:
- npm install -g npm
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start